Компоненты полностью не отрисовываются при npm start
htmlacademy-ecmascript/2072197-big-trip-simple-19 pull request #3
Opened 2022-12-11 22:10 UTC by A1exLove

2022-12-11 22:11 UTC, A1exLove commented
Компоненты не отрисовываются полностью. В чём может быть причина?

2022-12-14 16:40 UTC, ant1quar requested changes

2022-12-14 16:40 UTC, ant1quar commented on src/view/add-new-point-view.js
> +            <div class="event__type-item">
повторяется, стоит вынести в отдельную функцию

2022-12-14 16:40 UTC, ant1quar commented on src/view/add-new-point-view.js
> +          <div class="event__offer-selector">
тут тоже

2022-12-14 16:40 UTC, ant1quar commented on src/view/add-new-point-view.js
> +      <div class="event__field-group  event__field-group--time">
эта группа тоже

2022-12-14 16:40 UTC, ant1quar commented on src/view/edit-point-view.js
> +              <div class="event__type-item">
и тут

2022-12-14 16:40 UTC, ant1quar commented on src/view/edit-point-view.js
> +            <div class="event__offer-selector">
и тут

2022-12-14 16:40 UTC, ant1quar commented on src/view/sort-view.js
> +<div class="trip-sort__item  trip-sort__item--event">
тут тоже через цикл можно отрендерить

2022-12-14 16:46 UTC, A1exLove commented on src/view/add-new-point-view.js
> +            <div class="event__type-item">
Что повторяется?

2022-12-17 09:13 UTC, merged